using System;
using System.Reflection;

namespace System.Runtime.InteropServices
{
	/// <summary>Provides a callback mechanism for the assembly converter to inform the caller of the status of the conversion, and involve the caller in the conversion process itself.</summary>
	// Token: 0x02000943 RID: 2371
	[Guid("F1C3BF77-C3E4-11d3-88E7-00902754C43A")]
	[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
	[ComVisible(true)]
	public interface ITypeLibExporterNotifySink
	{
		/// <summary>Notifies the caller that an event occured during the conversion of an assembly.</summary>
		/// <param name="eventKind">An <see cref="T:System.Runtime.InteropServices.ExporterEventKind" /> value indicating the type of event.</param>
		/// <param name="eventCode">Indicates extra information about the event.</param>
		/// <param name="eventMsg">A message generated by the event.</param>
		// Token: 0x0600611A RID: 24858
		void ReportEvent(ExporterEventKind eventKind, int eventCode, string eventMsg);

		/// <summary>Asks the user to resolve a reference to another assembly.</summary>
		/// <param name="assembly">The assembly to resolve.</param>
		/// <returns>The type library for <paramref name="assembly" />.</returns>
		// Token: 0x0600611B RID: 24859
		[return: MarshalAs(UnmanagedType.Interface)]
		object ResolveRef(Assembly assembly);
	}
}
